[package]
name = "rust-ndarray"
version = "0.0.1"
edition = "2024"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies.ndarray]
version = "0.16.1"
features = ["matrixmultiply-threading"]

[dependencies.utils]
path = "../../common/rust"
